name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # каждые 12 часов
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-neon.svg?color_snake=#00FFD1&color_dots=#F400A1,#FFD500,#00FFB3,#00BFFF,#FF005C
            dist/snake-neon-dark.svg?palette=github-dark&color_snake=#00FFD1&color_dots=#F400A1,#FFD500,#00FFB3,#00BFFF,#FF005C

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
